### PR TITLE
Jsm/dont use scheme for model urls

### PR DESCRIPTION
**Pull request by JoshMcCullough**
For observation attachments and layers, the URL for a model is sent back from the API call, and is determined on the server. Existing code was using the server's request protocol which may not match that of the client side. This change does not use the server's request protocol and instead uses `//` which will match the browser's protocol. 

This is an issue if MAGE is used via HTTPS but proxied through to HTTP. The `observation.url` property, for example, would come back as `http://...` rather than `https://...`. This fixes that issue.

**Note:** this will work correctly in a browser but I'm not sure if other API callers will respect `//`. Another solution would be to add a configuration variable / env var e.g. `MAGE_CLIENT_URL_USE_HTTPS` which, when set to `true` would return `https` as the scheme/protocol rather than whatever is on the request. I leave that to the MAGE devs to determine which is the better fix.

### CODE REVIEW

**Comment by newmanw** [comment]
Are you seeing problems?  If so, what are you using to proxy?

**Comment by JoshMcCullough** [comment]
Yes, we are proxying MAGE requests and only support HTTPS. We are using NGINX, for example, but that is not really relevant. The problem is that HTTPS is proxied to the actual MAGE server which is listening on HTTP. So when the server builds the URL (`path`) using `req.getProtocol()`, it returns "http" since that is actually what the request URL's scheme is. But once this makes it back to the client (browser), the client uses this URL to manage attachments (and other things). But our proxy is not listening on HTTP, only HTTPS, so we end up with a 404 from NGINX.

We could fix this by listening for HTTP traffic in NGINX as well and proxying it appropriately, but IMO the MAGE server shouldn't be dictating the protocol that a client should use, so using `//` instead of `http[s]` fixes this in the browser. 

We could also fix this by running MAGE internally on HTTPS but we generally run internal APIs without SSL and use NGINX to proxy SSL traffic through.

**Comment by newmanw** [comment]
@jsalankey I believe it is relevant, you need to set X-Forwarded-Proto header.

https://expressjs.com/en/4x/api.html#req.protocol

I believe something like this will work for NGINX:

`proxy_set_header X-Forwarded-Proto`

**Comment by JoshMcCullough** [comment]
That's great -- didn't realize Express would support that. Will give it a try.

**Comment by JoshMcCullough** [comment]
That works -- closing this.

**Pull request closed without merging**
