### PR TITLE
move icon instead of renaming else it fails across devices

### PR DESCRIPTION
**Pull request by JoshMcCullough**
On linux systems if the `/tmp` mount-point is on a different device than where MAGE is installed, icon uploading fails since `fs.rename` is not permitted across devices. This fix uses `fs.move` instead, and overwrites the destination file.

### CODE REVIEW

**Comment by newmanw** [comment]
Currently MAGE assumes the file upload directory (/tmp) lives on the same filesystem.  This assumption is made to allow for quickly moving large files from the upload directory to its permanent home.  Although compatible, your change could lead to slower file upload processing.  We should allow users to configure where file uploads live.

Consider adding an ENV variable here with documentation about performance across file systems
[magerc.sh](../blob/master/environment/magerc.sh)

That is added to MAGE config here:
[env.js](../blob/master/environment/env.js)

Then configure multer to use that directory for file uploads.

In addition, there are other places MAGE handles file uploads, please ensure these are updated as well and don't forget about tests where possible.

**Comment by JoshMcCullough** [comment]
(For posterity, I recommend this PR plus your suggested config option for the final solution.)

**Comment by newmanw** [comment]
This pull request is incomplete, you are going to run into problems in other areas like user icon and avatar upload as well as layer uploads like KML and GeoPackage.  

If you are willing you can finish implementing the recommended solution to complete the pull request, or we can write an issue and address it at a later time.

**Comment by JoshMcCullough** [comment]
I only saw this one other occurrence of `fs.move` -- fixed it here. There are other occurrences of `fs.move` which do not clobber/overwrite, but I assume that is intentional so I did not touch them.

**Comment by JoshMcCullough** [comment]
@newmanw Pretty sure this can be merged, if you agree -- of course. Not sure why CI is failing though...

**Comment by newmanw** [comment]
Fixed by #58

**Pull request closed without merging**
